#!/bin/bash
#http://192.168.10.6/keyid={keyid}&secret={secret}&name={name}&rr={rr}&ipaddr={ipaddr}
old_ip="none"
sleep 10
while true
do
   ip=$(ubus call network.interface.wan status | grep \"address\" | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
   if [ "$ip" != "$old_ip" ]; then
       old_ip=$ip
       url="http://192.168.10.6/keyid=&secret=&name=iddc.cc&rr=@&ipaddr="$ip
       curl "$url"
   fi
   sleep 300
done
